apiVersion: v1
kind: Pod
metadata:
  name: mediawiki
spec:
  restartPolicy: Never
  containers:
  - name: mediawiki
    image: benhutchins/mediawiki
    ports:
    - containerPort: 80
      hostPort: 8001
      hostIP: 0.0.0.0
    env:
    - name: MEDIAWIKI_DB_HOST
      value: { get_input: host_ip }
    - name: MEDIAWIKI_DB_PORT
      value: { concat: ["", { get_property: [ mysqld1, port ]}] }
    - name: MEDIAWIKI_DB_USER
      value: root
    - name: MEDIAWIKI_DB_PASSWORD
      value: { concat: ["", { get_property: [ mysqld1, root_password ]}] }
    - name: MEDIAWIKI_SITE_NAME
      value: TestWiki
    - name: MEDIAWIKI_ADMIN_USER
      value: admin
    - name: MEDIAWIKI_ADMIN_PASS
      value: asdasd
    - name: MEDIAWIKI_SITE_LANG
      value: en
    - name: MEDIAWIKI_SITE_SERVER
      value: { concat: ["http://", { get_attribute: [ master_ip, aws_resource_id ] }, ":8001"] }
      